name: osim-core-windows

on: 
    push:
    schedule:
      - cron: '0 0 * * *' # daily

jobs:

    windows:

        env:
            numpy_version: '2.*'
            ezc3d_version: 1.6.3

        strategy:

            # matrix:
            #     url: 
            #       - "https://example.com/first"
            #       - "https://example.com/second"
            #     python_version: 
            #       - "3.13.*"
            #       - "3.14.*"
            #     numpy_version: ["2.*"]

            matrix:
                # os: [windows-2022]
                include:

                  - label: 'osim_jam_api_win64_py314'
                    python_version: '3.14.*'
                    user: mrrezaie
                    branch: opensim_jam
                    c3d_parser: 'None'
                    gui: 'OFF'

                  - label: 'osim_jam_gui_win64_py314'
                    python_version: '3.14.*'
                    user: mrrezaie
                    branch: opensim_jam
                    c3d_parser: 'ezc3d'
                    gui: 'ON'

                  - label: 'osim_org_gui_win64_py314'
                    python_version: '3.14.*'
                    user: opensim-org
                    branch: main
                    c3d_parser: 'ezc3d'
                    gui: 'ON'

        name: ${{ matrix.label }}
        runs-on: windows-latest # 2025
        # defaults:
        #     run:
        #         shell: powershell


        steps:

          - name: Test
            shell: bash
            run: |
                LABEL="${{ matrix.label }}"
                LAST_3_CHARACTERS="${LABEL: -3}"
                echo "Last 3 characters of label: $LAST_3_CHARACTERS"


          - name: Install SWIG
            run: |
                choco install swig --version 4.1.1 --yes --limit-output --allow-downgrade
                swig -swiglib
                choco list



          - name: Install Python ${{ matrix.python_version }}
            uses: actions/setup-python@v4
            with:
                python-version: ${{ matrix.python_version }}


          - name: Install NumPy 
            run: |
                python -m pip install --upgrade pip
                python -m pip install numpy==${{ env.numpy_version }} setuptools wheel




          # - name: Clone opensim-core repository
          #   run: |
          #       cd ~
          #       git clone ${{ matrix.url }} opensim-core
          #       # git clone https://github.com/mrrezaie/opensim-jam-core.git opensim-core
          #       # git clone https://github.com/opensim-org/opensim-core.git opensim-core
          #       # git clone https://github.com/opensim-jam-org/opensim-core.git opensim-core
          #       # git clone --single-branch --branch opensim-jam https://github.com/mrrezaie/opensim-core.git opensim-core




          - name: Checkout opensim-core repository
            uses: actions/checkout@v4
            with:
                repository: ${{ matrix.user }}/opensim-core
                path: opensim-core
                ref: ${{ matrix.branch }}


          - name: Copy to home
            run: |
                cp -r $env:GITHUB_WORKSPACE/opensim-core ~
                ls ~/opensim-core


          # - name: Cache opensim-core dependencies
          #   id: cache-dependencies
          #   uses: actions/cache@v4
          #   with:
          #       path: ~/install_deps
          #       key: ${{ runner.os }}-dependencies-${{ hashFiles('opensim-core/dependencies/*') }}


          - name: Build opensim-core dependencies
            # if: steps.cache-dependencies.outputs.cache-hit != 'true'
            run: |
                mkdir ~/build_deps
                chdir ~/build_deps
                
                cmake -E env CXXFLAGS="/W3 /MD" `
                    cmake ~/opensim-core/dependencies `
                    -G "Visual Studio 17 2022" `
                    -A x64 `
                    -DSUPERBUILD_ezc3d=ON `
                    -DOPENSIM_WITH_CASADI=ON `
                    -DCMAKE_INSTALL_PREFIX=~/install_deps

                cmake --build . --config Release --parallel 4











          # - name: Obtain opensim-core commit
          #   id: opensim-core-commit
          #   run: |
          #       cd opensim-core
          #       $opensim_core_commit=(git rev-parse HEAD)
          #       echo "hash=$opensim_core_commit" >> $GITHUB_OUTPUT
          #       echo $opensim_core_commit


          # - name: Cache opensim-core
          #   id: cache-core
          #   uses: actions/cache@v4
          #   with:
          #       path: ~/install_core
          #       key: ${{ runner.os }}-${{ steps.opensim-core-commit.outputs.hash }}




          - name: Build opensim-core
            # if: steps.cache-core.outputs.cache-hit != 'true'
            id: build
            run: |
                mkdir ~/build_core
                chdir ~/build_core
                
                cmake -E env CXXFLAGS="/W3 /MD -DSKIP_TIMING" `
                    cmake ~/opensim-core `
                    -G "Visual Studio 17 2022" `
                    -A x64 -DOPENSIM_DEPENDENCIES_DIR=~/install_deps `
                    -DOPENSIM_C3D_PARSER=${{ matrix.c3d_parser }} `
                    -DBUILD_PYTHON_WRAPPING=ON `
                    -DOPENSIM_WITH_CASADI=ON `
                    -DBUILD_JAVA_WRAPPING=ON `
                    -DBUILD_TESTING=OFF `
                    -DCMAKE_INSTALL_PREFIX=~/install_core
                
                cmake --build . --config Release --parallel 4
                cmake --install .


                # $env:match = cmake -L . | Select-String -Pattern OPENSIM_QUALIFIED_VERSION
                # $OPENSIM_VERSION = $env:match.split('=')[1]
                # echo "OPENSIM_VERSION=$OPENSIM_VERSION" >> $env:GITHUB_ENV
                

          # - name: Version
          #   run: echo ${{ env.OPENSIM_VERSION }}





          - name: Set current date
            id: date
            run: echo "date=$(date +'%Y%m%d')" >> $env:GITHUB_ENV






          - name: Clone opensim-models Geometry
            if: ${{ matrix.gui == 'OFF' }}
            uses: actions/checkout@v4
            with:
                repository: opensim-org/opensim-models
                path: 'opensim-models'
                sparse-checkout: 'Geometry'
                # sparse-checkout-cone-mode: false




          - name: Include Geometry folder
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                cp -r $env:GITHUB_WORKSPACE/opensim-models/Geometry ~/install_core
                ls ~/install_core




          - name: Build opensim wheel file
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                chdir ~/install_core/sdk/Python
                python setup.py bdist_wheel
                # pip install ~/install_core/sdk/Python/dist/*.whl




          - name: Checkout ezc3d main
            if: ${{ matrix.gui == 'OFF' }}
            uses: actions/checkout@v4
            with:
                repository: pyomeca/ezc3d
                path: ezc3d
                ref: Release_${{ env.ezc3d_version }}

          - name: Path
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                cp -r $env:GITHUB_WORKSPACE/ezc3d ~
                ls ~
                ls ~/ezc3d


          - name: Install scikit-build and wheel
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                python -m pip install --upgrade pip
                python -m pip install scikit-build wheel


          - name: Build ezc3d (wheel file)
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                chdir ~/ezc3d
                python setup.py bdist_wheel -- -G"Visual Studio 17 2022" -A x64


          # - name: Find wheel file
          #   shell: pwsh
          #   run: |
          #       chdir ~/install_core/sdk/Python/dist
          #       $wheel = Get-ChildItem -Path dist -Filter *.whl | Select-Object -First 1
          #       echo "OSIM_WHEEL=$($wheel.Name)" >> $env:GITHUB_ENV

          #       chdir ~/ezc3d/dist/
          #       $wheel = Get-ChildItem -Path dist -Filter *.whl | Select-Object -First 1
          #       echo "EZC3D_WHEEL=$($wheel.Name)" >> $env:GITHUB_ENV

          # - name: Use the wheel name
          #   run: |
          #       echo "OpenSim wheel is $env:OSIM_WHEEL"
          #       echo "Ezc3d wheel is $env:EZC3D_WHEEL"


          - name: Clean and copy the wheel files
            if: ${{ matrix.gui == 'OFF' }}
            run: |
                chdir ~/ezc3d/dist/
                ls .
                rm -r ezc3d-${{ env.ezc3d_version }}/ezc3d-${{ env.ezc3d_version }}.data
                python -m wheel pack ezc3d-${{ env.ezc3d_version }}

                mkdir ~/wheel_files
                cp ~/install_core/sdk/Python/dist/*.whl ~/wheel_files
                cp ~/ezc3d/dist/*.whl ~/wheel_files


          - name: Upload opensim API and ezc3d wheel files
            if: ${{ matrix.gui == 'OFF' }}
            uses: actions/upload-artifact@v4
            with:
                name: ${{ matrix.label }}-${{ env.date }}
                path: ~/wheel_files
                # path: |
                #     ~/install_core/sdk/Python/dist/*.whl
                #     ~/ezc3d/dist/*.whl














          - name: Set up JDK 1.8
            if: ${{ matrix.gui == 'ON' }}
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: 8






          - name: Install Netbeans 12.3
            if: ${{ matrix.gui == 'ON' }}
            run: |
                (New-Object System.Net.WebClient).DownloadFile("https://archive.apache.org/dist/netbeans/netbeans/12.3/Apache-NetBeans-12.3-bin-windows-x64.exe", "Apache-NetBeans-12.3-bin-windows-x64.exe")
                $expectedHash = "0695d87d9c72dcf3738672ba83eb273dda02066fa5eee80896cb6ccf79175840367a13d22ab3cb9838dffaa9a219dd1f73aee0e27c085e5310da2e3bbbc92b2c"
                $hashFromFile = Get-FileHash -Algorithm SHA512 -Path .\Apache-NetBeans-12.3-bin-windows-x64.exe
                if (($hashFromFile.Hash) -ne ($expectedHash)) { Write-Error "Hash doesn't match." }
                .\Apache-NetBeans-12.3-bin-windows-x64.exe --silent | Out-Null # This installer is gregarious.
                echo "ANT_HOME=C:\\Program Files\\NetBeans-12.0\\netbeans\\extide\\ant" >> $GITHUB_ENV


          # - name: Setup NetBeans distribution
          #   uses: cjmach/setup-netbeans-action@v2.1
          #   with:
          #     version: '18'




          # - name: Clone opensim-gui repository
          #   uses: actions/checkout@v4
          #   with:
          #       repository: opensim-org/opensim-gui
          #       path: 'opensim-gui'


          - name: Clone opensim-gui repository
            if: ${{ matrix.gui == 'ON' }}
            run: |
                cd ~
                git clone https://github.com/opensim-org/opensim-gui.git opensim-gui


          - name: Update submodules
            if: ${{ matrix.gui == 'ON' }}
            run: |
                cd ~/opensim-gui
                git submodule update --init --recursive -- opensim-visualizer Gui/opensim/threejs

                git clone https://github.com/opensim-org/opensim-models.git opensim-models
                # git clone https://github.com/opensim-org/opensim-visualizer.git opensim-visualizer
                # git clone https://github.com/opensim-org/three.js.git Gui/opensim/threejs

                dir ~/opensim-gui/opensim-models





          - name: Build GUI
            if: ${{ matrix.gui == 'ON' }}
            id: build-gui
            run: |
                mkdir ~/build_gui
                chdir ~/build_gui

                cmake ~/opensim-gui/ `
                -G"Visual Studio 17 2022" -A x64 `
                -DCMAKE_PREFIX_PATH=~/install_core `
                -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=C:/Program Files/NetBeans-12.3/netbeans;-Dnbplatform.default.harness.dir=C:/Program Files/NetBeans-12.3/netbeans/harness"
                cmake --build . --target CopyOpenSimCore --config Release
                cmake --build . --target CopyModels --config Release
                cmake --build . --target PrepareInstaller --config Release
                cmake --build . --target CopyJRE --config Release
                cmake --build . --target CopyVisualizer --config Release



          # - name: Build GUI installer
          #   run: |
          #       cd ~/opensim-gui/Gui/opensim/dist/installer
          #       makensis.exe make_installer.nsi


          # - name: Paths
          #   run: |
          #       dir ~/
          #       dir $env:GITHUB_WORKSPACE
          #       dir ~/opensim-gui/Gui/opensim/dist/installer





          - name: Upload GUI installer
            if: ${{ matrix.gui == 'ON' }}
            uses: actions/upload-artifact@v4
            with:
                name: ${{ matrix.label }}-${{ env.date }}
                path: ~/opensim-gui/Gui/opensim/dist/installer/opensim
                # path: ~/opensim-gui/Gui/opensim/dist/installer
                # path: ~/install_core/sdk/Python/dist/*.whl
